version: '3.3'

services:
  mysql:
    image: mysql:5.7
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./.docker/mysql57/log:/var/log/mysql
      - ./.docker/mysql57/data:/var/lib/mysql
      - ./.docker/mysql57/conf:/etc/mysql/conf.d
    ports:
      - "3307:3306"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8090:8080"

  redis:
    image: redis
    command: redis-server
    # command: redis-server --requirepass 123456
    volumes:
      - ./.docker/redis/config/redis.conf:/etc/redis/redis.conf
      - ./.docker/redis/data:/data
    ports:
      - "6379:6379"

  mongo:
    image: mongo
    restart: always
    volumes:
      - ./.docker/mongodb/data:/data/db
      - ./.docker/mongodb/dump:/dump
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - mongo
